
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      name: main
      port: 8080
      targetPort: 8080
      nodePort: 30900
    - protocol: TCP
      name: agent
      port: 50000
      targetPort: 50000
  type: NodePort
