
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8081'
spec:
  selector:
    app: nexus
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30901
  type: NodePort
