
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "sonarqube"
        - name: POSTGRES_PASSWORD
          value: "sonarqube"
        - name: POSTGRES_DB
          value: "sonarqube"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc
