
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonar
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30902
  type: NodePort
