apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:10.6-community
        ports:
        - containerPort: 9000
        env:
        - name: SONAR_JDBC_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sonarqube-config
              key: SONAR_JDBC_USERNAME
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sonarqube-config
              key: SONAR_JDBC_PASSWORD
        - name: SONAR_JDBC_URL
          valueFrom:
            configMapKeyRef:
              name: sonarqube-config
              key: SONAR_JDBC_URL
        volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-logs
          mountPath: /opt/sonarqube/logs
        - name: sonarqube-extensions
          mountPath: /opt/sonarqube/extensions
      volumes:
      - name: sonarqube-data
        persistentVolumeClaim:
          claimName: sonarqube-data-pvc
      - name: sonarqube-logs
        persistentVolumeClaim:
          claimName: sonarqube-logs-pvc
      - name: sonarqube-extensions
        persistentVolumeClaim:
          claimName: sonarqube-extensions-pvc
