---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-data-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: sonarqube-data-pvc
    namespace: sonar
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/data/sonarqube_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: color
          operator: In
          values:
          - orange
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data-pvc
  namespace: sonar
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-logs-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: sonarqube-logs-pvc
    namespace: sonar
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/data/sonarqube_logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: color
          operator: In
          values:
          - orange

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-logs-pvc
  namespace: sonar
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-extensions-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: sonarqube-extensions-pvc
    namespace: sonar
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/data/sonarqube_extensions
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: color
          operator: In
          values:
          - orange

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-extensions-pvc
  namespace: sonar
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
