apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonar
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '9000'
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30901
  type: NodePort
