
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["chown -R 1000:1000 /jenkins-docker-certs /jenkins-data"]
        volumeMounts:
        - name: jenkins-data
          mountPath: /jenkins-data
        - name: jenkins-docker-certs
          mountPath: /jenkins-docker-certs
      containers:
      - name: jenkins
        image: manrala/cloudbees:2.475-jdk21-v1
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: DOCKER_HOST
          value: "tcp://docker:2376"
        - name: DOCKER_CERT_PATH
          value: "/certs/client"
        - name: DOCKER_TLS_VERIFY
          value: "1"
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
        - name: jenkins-docker-certs
          mountPath: /certs/client
          readOnly: true
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-data-pvc
      - name: jenkins-docker-certs
        persistentVolumeClaim:
          claimName: jenkins-docker-certs-pvc
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
